name = "Entropicraft"
author = "aranoided"
version = "2026.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0b287e3d6e649300328c907e0618ffddc35e5e9d65629de477629d1e1fec17f"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
