name = "Entropicraft"
author = "aranoided"
version = "2026.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d0361c885920203cf5335b3eca9680de5f655efa5c55b516a5ce87b222ad10c4"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
